# (c) Mihai Chiroiu - CDCI
.PHONY: containers
containers:
	make -C base
	make -C dvwa_docker
	make -C kali
	make -C iot_lab03
	make -C dhcpd_lab03
	make -C dns_lab03
	make -C crypto_lab05
	make -C exfiltration_lab06 
	make -C snort_lab07 
	make -C exam_docker
