# (c) Mihai Chiroiu - CDCI
.PHONY: containers
containers:
	make -C cdci_base
	make -C kali
	make -C lab03_dwva
	make -C lab03_iot
	make -C lab03_dhcpd
	make -C lab03_dns
	make -C lab05_crypto
	make -C lab06_exfiltration
	make -C lab07_snort
	make -C exam_docker
